import { Container, CssBaseline, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>SUNNAH</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://img.icons8.com/fluency/48/000000/pen-1.png"
        />
      </Head>
      <CssBaseline />
      <Typography>NI</Typography>
    </Container>
  );
};

export default Home;
